feat: info-bites
KILTprotocol/kilt-resources pull request #19
Opened 2024-03-13 21:20 UTC by aybarsayan

## feat: Info Bites Tamplate KILTProtocol/ticket#3205
Please include a summary of the changes provided with this pull request and which issue has been fixed. 
Please also provide some context if necessary.

## How to test:
Please provide a brief step-by-step instruction.
If necessary provide information about dependencies (specific configuration, branches, database dumps, etc.)

- Step 1
- Step 2
- etc.

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)
    * Either PR or Ticket to update [the Docs](https://github.com/KILTprotocol/docs)
    * Link the PR/Ticket here

2024-03-18 14:42 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +# July Info Bites
@aybarsayan Is the name and file name correct? July 2023? Though I guess it doesn't matter

2024-03-18 14:43 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +What is DIDs?
```suggestion
What are DIDs? 
```

2024-03-18 14:48 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +- In our current system, we have to rely on centralized authority (such as government) or singular monopoly services (Google, Facebook, etc.) for our digital identity. They are storing our data in ce
```suggestion
- Currently, we have to rely on a centralized authority (such as a government) or singular monopoly (Google, Facebook, etc.) for our digital identity. They store our data in centralized databases and control our data. 
```

2024-03-18 14:51 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +- But wait, there's more! A Full DID comes with some special powers. It supports an attestation key, which is used to write CTypes and attestations on the blockchain. It's like leaving your mark in t
I get the impression that this is for beginners, will they have any idea what a CType or an attestation is?

2024-03-18 14:52 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +🧐 Who is? 🧐
Do you mean to have the "Delloite" part here?

2024-03-18 14:54 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +- Deloitte offers integrated services that include Audit & Assurance, Consulting, Financial Advisory, Risk Advisory and Tax & Legal. Our approach combines insight and innovation from multiple discipl
```suggestion
- Deloitte offers integrated services that include Audit & Assurance, Consulting, Financial Advisory, Risk Advisory and Tax & Legal. Their approach combines insight and innovation from multiple disciplines with business and industry knowledge to help clients excel anywhere in the world.
```

Unless this is supposed to be said by someone from Delloite?

2024-03-18 14:55 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +How Delloite uses KILT?
```suggestion
How does Delloite use KILT?
```

2024-03-18 14:58 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +- Deloitte Consulting AG announced the integration of KILT blockchain technology for issuing reusable digital credentials to support KYC and KYB processes. These credentials have multiple use cases i
```suggestion
- Deloitte Consulting AG announced the integration of KILT blockchain technology for issuing reusable digital credentials to support  Know Your Client (KYC) and Know Your Business (KYB) processes. These credentials have multiple use cases, including regulatory compliance for banking and Decentralized Finance (DeFi), age verification for e-commerce, private logins and fundraising.
```

2024-03-18 14:58 UTC, ChrisChinchilla requested changes
@aybarsayan Few small tweaks

2024-03-18 15:01 UTC, aybarsayan commented on info-bites/july-2023.md
> +# July Info Bites
Yes, this ones are already used. I imported them to be a placeholder 😊

2024-03-18 15:06 UTC, aybarsayan commented on info-bites/july-2023.md
> +- But wait, there's more! A Full DID comes with some special powers. It supports an attestation key, which is used to write CTypes and attestations on the blockchain. It's like leaving your mark in t
I was actually created for Ctypes too in earlier Info Bites

2024-03-18 15:08 UTC, aybarsayan commented on info-bites/july-2023.md
> +🧐 Who is? 🧐
Yes I was 😊

2024-03-18 15:27 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +🧐 Who is? 🧐
OK @aybarsayan then…

```suggestion
🧐 Who is Deloitte? 🧐
```

2024-03-18 15:27 UTC, ChrisChinchilla commented on info-bites/july-2023.md
> +Who is Delloite?
```suggestion
```

2024-03-20 08:53 UTC, ggera approved these changes
I would make two subdirecotries `img` and `md` so that the root directory won't be floded with new files

2024-03-22 13:56 UTC, merged